<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ShopRedesign04" name="com.tcs.BsiShopRedesign.sprint8.ApplyMemberAccount" tests="3" failures="1" timestamp="6 Sep 2018 17:03:03 GMT" time="763.228" errors="0">
  <testcase name="signIn" time="15.797" classname="com.tcs.BsiShopRedesign.sprint8.ApplyMemberAccount"/>
  <testcase name="applyMemberAccountBelowBandNine" time="716.455" classname="com.tcs.BsiShopRedesign.sprint8.ApplyMemberAccount">
    <failure type="java.lang.AssertionError" message="Click Checkout was unsuccessful">
      <![CDATA[java.lang.AssertionError: Click Checkout was unsuccessful
	at org.testng.Assert.fail(Assert.java:94)
	at com.tcs.BsiShopRedesign.utilities.CommonHelper.reportFailure(CommonHelper.java:66)
	at com.tcs.BsiShopRedesign.pages.BasketPage.clickCheckout(BasketPage.java:457)
	at com.tcs.BsiShopRedesign.sprint8.ApplyMemberAccount.applyMemberAccountBelowBandNine(ApplyMemberAccount.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- applyMemberAccountBelowBandNine -->
  <testcase name="applyMemberAccountBandNineAbove" time="30.976" classname="com.tcs.BsiShopRedesign.sprint8.ApplyMemberAccount"/>
</testsuite> <!-- com.tcs.BsiShopRedesign.sprint8.ApplyMemberAccount -->
